# Generated by Django 4.0.3 on 2022-03-22 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0003_remove_pessoa_ativa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='senha',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
