# Generated by Django 4.0.3 on 2022-03-22 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0004_alter_pessoa_senha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='nome_completo',
            new_name='login',
        ),
    ]
